type Query {
  incidents(status: IncidentStatus, labels: [Int!]): [Incident!]!
  incident(id: Int!): Incident!
  incidentLabels: [IncidentLabel!]!
}

type Mutation {
  createIncident(input: CreateIncidentInput!): Incident!
  addIncidentHistory(input: CreateIncidentHistoryInput!): IncidentHistory!
}

type Subscription {
  newIncident: Incident!
}

scalar DateTime
type Incident {
  id: Int!
  information: String
  status: IncidentStatus!
  locationAddress: String
  locationLat: Float!
  locationLng: Float!
  label: IncidentLabel!
  createdBy: User!
  histories: [IncidentHistory]!
  historiesCount: Int!
  # imageUrls: [String!]!
  # userUpvotes: [User!]!
  createdAt: DateTime!
  updatedAt: DateTime!
}

enum IncidentStatus {
  OPEN
  CLOSED
}

input CreateIncidentInput {
  information: String!
  locationAddress: String
  locationLat: Float!
  locationLng: Float!
  # label ID
  label: Int!
}


type IncidentLabel {
  id: Int!
  name: String!
  icon: String!
  relatedOrganizations: [Organization]!
}


type IncidentHistory {
  id: Int!
  content: String
  type: IncidentHistoryType!
  createdBy: User!
  createdAt: DateTime!
}

input CreateIncidentHistoryInput {
  content: String
  type: IncidentHistoryType!
  incidentId: Int!
}

enum IncidentHistoryType {
  FOLLOW_UP
  COMMENT
}
